window.HIREFLOW_DATA = {
  jobs: [
    {
      id: "job-001",
      title: "Senior Product Designer",
      companyId: "company-aurora",
      company: "Aurora Labs",
      logo: "assets/logo-aurora.svg",
      location: "Remote",
      type: "Full-time",
      level: "Senior",
      salaryMin: 118,
      salaryMax: 145,
      posted: "2h ago",
      skills: ["Figma", "Design Systems", "Research", "SaaS"],
      description: "Lead end-to-end product design for a fast-growing analytics platform used by operations teams across North America and Europe.",
      requirements: ["6+ years designing B2B SaaS products", "Strong systems thinking and visual craft", "Comfortable running research and synthesis", "Portfolio showing shipped product impact"],
      responsibilities: ["Own discovery through polished delivery", "Partner with product and engineering leads", "Evolve Aurora's component library", "Mentor two mid-level designers"]
    },
    {
      id: "job-002",
      title: "Frontend Engineer",
      companyId: "company-nova",
      company: "NovaWorks",
      logo: "assets/logo-nova.svg",
      location: "San Francisco",
      type: "Remote",
      level: "Mid-level",
      salaryMin: 105,
      salaryMax: 132,
      posted: "5h ago",
      skills: ["JavaScript", "React", "Accessibility", "CSS"],
      description: "Build performant client-side experiences for hiring teams managing high-volume pipelines.",
      requirements: ["4+ years frontend engineering experience", "Deep JavaScript and CSS knowledge", "Accessibility-first mindset", "Experience with analytics instrumentation"],
      responsibilities: ["Ship responsive product interfaces", "Improve design system primitives", "Partner with product designers", "Optimize bundle size and runtime performance"]
    },
    {
      id: "job-003",
      title: "Freelance Webflow Developer",
      companyId: "company-lattice",
      company: "Lattice Studio",
      logo: "assets/logo-lattice.svg",
      location: "Remote",
      type: "Freelance",
      level: "Mid-level",
      salaryMin: 55,
      salaryMax: 85,
      posted: "1d ago",
      skills: ["Webflow", "CMS", "GSAP", "SEO"],
      description: "Create polished marketing sites and landing pages for venture-backed startups on a project basis.",
      requirements: ["Portfolio of Webflow builds", "Comfort with custom code embeds", "Clear async communication", "SEO and performance fundamentals"],
      responsibilities: ["Build responsive Webflow pages", "Connect CMS collections", "Animate product storytelling sections", "Handoff documentation to clients"]
    },
    {
      id: "job-004",
      title: "Data Analyst",
      companyId: "company-greenline",
      company: "Greenline Finance",
      logo: "assets/logo-greenline.svg",
      location: "New York",
      type: "Full-time",
      level: "Junior",
      salaryMin: 72,
      salaryMax: 91,
      posted: "1d ago",
      skills: ["SQL", "Looker", "Excel", "Finance"],
      description: "Turn finance and product data into clear reporting for leadership and customer-facing teams.",
      requirements: ["2+ years in data or finance operations", "Strong SQL fundamentals", "Dashboarding experience", "Excellent written communication"],
      responsibilities: ["Maintain executive dashboards", "Analyze product usage trends", "Support forecasting workflows", "Translate analysis into recommendations"]
    },
    {
      id: "job-005",
      title: "Backend Engineer, Payments",
      companyId: "company-pulse",
      company: "PulsePay",
      logo: "assets/logo-pulse.svg",
      location: "Austin",
      type: "Full-time",
      level: "Senior",
      salaryMin: 125,
      salaryMax: 158,
      posted: "2d ago",
      skills: ["Node.js", "PostgreSQL", "APIs", "Payments"],
      description: "Design reliable payment services for marketplaces, subscriptions, and global invoices.",
      requirements: ["5+ years backend development", "Experience with transactional systems", "Strong API design instincts", "Security and compliance awareness"],
      responsibilities: ["Own payment service architecture", "Improve observability and alerting", "Review critical code paths", "Collaborate with risk and finance teams"]
    },
    {
      id: "job-006",
      title: "Growth Marketing Contractor",
      companyId: "company-brightpath",
      company: "BrightPath",
      logo: "assets/logo-brightpath.svg",
      location: "Remote",
      type: "Contract",
      level: "Lead",
      salaryMin: 75,
      salaryMax: 110,
      posted: "2d ago",
      skills: ["Lifecycle", "HubSpot", "Experimentation", "Copywriting"],
      description: "Run acquisition and lifecycle experiments for a fast-scaling education marketplace.",
      requirements: ["Experience owning growth experiments", "Strong lifecycle marketing background", "Comfort with analytics tools", "Crisp copywriting skills"],
      responsibilities: ["Launch weekly experiments", "Improve nurture journeys", "Report funnel performance", "Coordinate with design and sales"]
    },
    {
      id: "job-007",
      title: "UX Researcher",
      companyId: "company-aurora",
      company: "Aurora Labs",
      logo: "assets/logo-aurora.svg",
      location: "London",
      type: "Contract",
      level: "Senior",
      salaryMin: 92,
      salaryMax: 120,
      posted: "3d ago",
      skills: ["Interviews", "Usability", "B2B", "Research Ops"],
      description: "Shape discovery for complex B2B workflows through generative and evaluative research.",
      requirements: ["5+ years UX research experience", "Strong facilitation skills", "Experience with enterprise users", "Clear storytelling with evidence"],
      responsibilities: ["Plan quarterly research roadmap", "Run customer interviews", "Synthesize insights for teams", "Maintain research repository"]
    },
    {
      id: "job-008",
      title: "Mobile App Developer",
      companyId: "company-nova",
      company: "NovaWorks",
      logo: "assets/logo-nova.svg",
      location: "Berlin",
      type: "Remote",
      level: "Mid-level",
      salaryMin: 88,
      salaryMax: 118,
      posted: "3d ago",
      skills: ["React Native", "TypeScript", "iOS", "Android"],
      description: "Build mobile workflows that help freelance teams track work, contracts, and payments.",
      requirements: ["3+ years mobile app experience", "React Native production experience", "Strong TypeScript habits", "App store release familiarity"],
      responsibilities: ["Ship cross-platform features", "Improve offline flows", "Debug device-specific issues", "Collaborate with API engineers"]
    },
    {
      id: "job-009",
      title: "Brand Designer",
      companyId: "company-lattice",
      company: "Lattice Studio",
      logo: "assets/logo-lattice.svg",
      location: "Remote",
      type: "Freelance",
      level: "Senior",
      salaryMin: 60,
      salaryMax: 95,
      posted: "4d ago",
      skills: ["Brand Systems", "Illustration", "Pitch Decks", "Identity"],
      description: "Create memorable brand systems for seed-stage companies preparing launches and fundraises.",
      requirements: ["Strong brand portfolio", "Comfort with fast client cycles", "Great typography and layout sense", "Ability to present rationale clearly"],
      responsibilities: ["Design visual identity systems", "Create launch assets", "Build investor deck templates", "Collaborate with studio strategists"]
    },
    {
      id: "job-010",
      title: "DevOps Engineer",
      companyId: "company-pulse",
      company: "PulsePay",
      logo: "assets/logo-pulse.svg",
      location: "Remote",
      type: "Full-time",
      level: "Senior",
      salaryMin: 122,
      salaryMax: 152,
      posted: "4d ago",
      skills: ["AWS", "Terraform", "CI/CD", "Kubernetes"],
      description: "Keep a payments platform resilient, observable, and ready for international scale.",
      requirements: ["Production cloud infrastructure experience", "Terraform or similar IaC expertise", "Kubernetes operating knowledge", "Strong incident response habits"],
      responsibilities: ["Improve deployment pipelines", "Harden cloud infrastructure", "Tune observability systems", "Lead reliability reviews"]
    },
    {
      id: "job-011",
      title: "Customer Success Manager",
      companyId: "company-brightpath",
      company: "BrightPath",
      logo: "assets/logo-brightpath.svg",
      location: "New York",
      type: "Full-time",
      level: "Mid-level",
      salaryMin: 82,
      salaryMax: 105,
      posted: "5d ago",
      skills: ["Onboarding", "CRM", "Education", "Renewals"],
      description: "Own customer onboarding and expansion for growing education providers using BrightPath.",
      requirements: ["3+ years customer success experience", "Strong presentation skills", "CRM fluency", "Ability to manage complex accounts"],
      responsibilities: ["Lead onboarding programs", "Track customer health", "Coordinate renewal plans", "Share customer feedback with product"]
    },
    {
      id: "job-012",
      title: "AI Prompt Engineer",
      companyId: "company-signal",
      company: "SignalForge",
      logo: "assets/logo-signal.svg",
      location: "Remote",
      type: "Contract",
      level: "Lead",
      salaryMin: 115,
      salaryMax: 145,
      posted: "5d ago",
      skills: ["LLMs", "Evaluation", "Prompting", "Python"],
      description: "Design, test, and improve prompt systems for AI-assisted knowledge workflows.",
      requirements: ["Hands-on LLM product experience", "Evaluation design skills", "Strong writing and systems thinking", "Basic scripting ability"],
      responsibilities: ["Create prompt frameworks", "Build evaluation datasets", "Analyze model outputs", "Document best practices"]
    },
    {
      id: "job-013",
      title: "Junior QA Tester",
      companyId: "company-greenline",
      company: "Greenline Finance",
      logo: "assets/logo-greenline.svg",
      location: "Austin",
      type: "Full-time",
      level: "Junior",
      salaryMin: 52,
      salaryMax: 68,
      posted: "6d ago",
      skills: ["Manual QA", "Bug Reports", "Regression", "Jira"],
      description: "Support product quality across web and internal finance tools with thoughtful manual testing.",
      requirements: ["1+ year testing software", "Clear bug reporting", "Attention to detail", "Interest in automation"],
      responsibilities: ["Run regression passes", "Write test cases", "Verify bug fixes", "Support release readiness"]
    },
    {
      id: "job-014",
      title: "Technical Writer",
      companyId: "company-signal",
      company: "SignalForge",
      logo: "assets/logo-signal.svg",
      location: "Berlin",
      type: "Freelance",
      level: "Mid-level",
      salaryMin: 58,
      salaryMax: 84,
      posted: "6d ago",
      skills: ["Docs", "APIs", "AI", "Editing"],
      description: "Write clear product docs, API guides, and onboarding material for technical AI users.",
      requirements: ["Technical writing samples", "Ability to understand APIs", "Strong editorial judgment", "Comfort interviewing engineers"],
      responsibilities: ["Create user guides", "Maintain API references", "Edit release notes", "Improve onboarding content"]
    },
    {
      id: "job-015",
      title: "Product Manager",
      companyId: "company-nova",
      company: "NovaWorks",
      logo: "assets/logo-nova.svg",
      location: "London",
      type: "Full-time",
      level: "Lead",
      salaryMin: 128,
      salaryMax: 162,
      posted: "1w ago",
      skills: ["Roadmaps", "B2B", "Analytics", "Discovery"],
      description: "Lead product strategy for marketplace collaboration tools used by agencies and freelancers.",
      requirements: ["5+ years product management", "B2B marketplace experience", "Strong product discovery practice", "Comfort with data-informed decisions"],
      responsibilities: ["Set roadmap priorities", "Lead customer discovery", "Define product requirements", "Measure shipped feature impact"]
    },
    {
      id: "job-016",
      title: "Social Media Manager",
      companyId: "company-brightpath",
      company: "BrightPath",
      logo: "assets/logo-brightpath.svg",
      location: "Remote",
      type: "Freelance",
      level: "Junior",
      salaryMin: 38,
      salaryMax: 58,
      posted: "1w ago",
      skills: ["Content", "Community", "Canva", "Analytics"],
      description: "Grow BrightPath's social presence with practical content for educators and training teams.",
      requirements: ["Social content portfolio", "Strong editing instincts", "Comfort reading analytics", "Reliable publishing cadence"],
      responsibilities: ["Plan weekly content", "Create short-form assets", "Engage community replies", "Report channel performance"]
    },
    {
      id: "job-017",
      title: "Security Engineer",
      companyId: "company-pulse",
      company: "PulsePay",
      logo: "assets/logo-pulse.svg",
      location: "San Francisco",
      type: "Full-time",
      level: "Senior",
      salaryMin: 136,
      salaryMax: 174,
      posted: "1w ago",
      skills: ["AppSec", "Threat Modeling", "SOC 2", "Cloud"],
      description: "Protect customer funds and data by strengthening application and cloud security controls.",
      requirements: ["Application security experience", "Threat modeling practice", "Cloud security familiarity", "Clear risk communication"],
      responsibilities: ["Review product designs", "Run security assessments", "Improve control evidence", "Guide secure engineering practices"]
    },
    {
      id: "job-018",
      title: "No-Code Automation Specialist",
      companyId: "company-lattice",
      company: "Lattice Studio",
      logo: "assets/logo-lattice.svg",
      location: "Remote",
      type: "Contract",
      level: "Mid-level",
      salaryMin: 64,
      salaryMax: 92,
      posted: "1w ago",
      skills: ["Zapier", "Airtable", "Make", "Operations"],
      description: "Build internal automation systems for clients who need cleaner operations without custom software.",
      requirements: ["Experience with automation tools", "Comfort mapping business processes", "Strong testing discipline", "Client-facing communication"],
      responsibilities: ["Audit current workflows", "Build automations", "Create documentation", "Train client operators"]
    }
  ],
  companies: [
    {
      id: "company-aurora",
      name: "Aurora Labs",
      logo: "assets/logo-aurora.svg",
      location: "Remote-first",
      industry: "Analytics SaaS",
      size: "120-180 employees",
      openRoles: 2,
      description: "Aurora Labs builds workflow intelligence tools for operations teams that need cleaner decisions from messy data."
    },
    {
      id: "company-nova",
      name: "NovaWorks",
      logo: "assets/logo-nova.svg",
      location: "San Francisco, CA",
      industry: "Freelance Operations",
      size: "80-120 employees",
      openRoles: 3,
      description: "NovaWorks helps distributed freelance teams manage projects, contracts, communication, and payments in one place."
    },
    {
      id: "company-lattice",
      name: "Lattice Studio",
      logo: "assets/logo-lattice.svg",
      location: "Remote studio",
      industry: "Creative Services",
      size: "20-35 employees",
      openRoles: 4,
      description: "Lattice Studio partners with startups on brand systems, launch sites, automation, and high-craft digital experiences."
    },
    {
      id: "company-greenline",
      name: "Greenline Finance",
      logo: "assets/logo-greenline.svg",
      location: "New York, NY",
      industry: "Fintech",
      size: "200-320 employees",
      openRoles: 2,
      description: "Greenline Finance creates simple planning and reporting products for modern finance teams."
    },
    {
      id: "company-pulse",
      name: "PulsePay",
      logo: "assets/logo-pulse.svg",
      location: "Austin, TX",
      industry: "Payments",
      size: "150-240 employees",
      openRoles: 3,
      description: "PulsePay gives growing marketplaces flexible payment infrastructure, subscriptions, invoicing, and risk tooling."
    },
    {
      id: "company-brightpath",
      name: "BrightPath",
      logo: "assets/logo-brightpath.svg",
      location: "Hybrid",
      industry: "Education",
      size: "60-90 employees",
      openRoles: 3,
      description: "BrightPath connects education providers with learners through smarter enrollment, content, and student success workflows."
    },
    {
      id: "company-signal",
      name: "SignalForge",
      logo: "assets/logo-signal.svg",
      location: "Berlin, Germany",
      industry: "AI Tooling",
      size: "45-70 employees",
      openRoles: 2,
      description: "SignalForge builds practical AI tools for knowledge teams, with an emphasis on evaluation, trust, and documentation."
    }
  ]
};
